export const ADD_COUNTER = 'add_counter'
export const ADD_TO_CART = 'add_to_cart'
export const ADD_TO_COLLECTION = 'addtocollection'
export const COLLECTION_IS_CHECKED = 'collectionischecked'
export const SET_LOADING = 'setLoading'
